### ISSUE TITLE
Example with CupertinoTabView

### ISSUE THREAD

**Issue by diogox** [kspo/super_cupertino_navigation_bar#2]
Hi!

Thanks for making this.

I'm new to flutter development, and I'm trying to use your widget with iOS-like Tabs at the bottom of the screen.

I've iterated on getting both things to work together a few times, but no luck.

I was wondering if you could give it a shot and make it available as an example?

I appreciate any help you can provide 🙏

**Comment by diogox** [comment]
![simulator_screenshot_D1D2E827-1B14-4E57-AEF4-9D96C7370D80](https://github.com/kspo/super_cupertino_navigation_bar/assets/13244408/db65561d-30e5-4231-87ba-6ca2b2ff5936)

It should look something like this, but work - mine doesn't. Different issues on different iterations 😅

**Comment by kspo** [comment]
Hello @diogox. It's nice to see you here. I released the second version of the package today. There are examples in the "example" folder that should meet your needs. I hope these will be helpful. Feel free to reach out if you have any other requirements. Have fun ☺️
