### ISSUE TITLE
Dynamic body length

### ISSUE THREAD

**Issue by eikebartels** [kspo/super_cupertino_navigation_bar#4]
Hello, thanks for this sweet package. It works quite well. 

I have a huge list which I would like to display. How can this be archived with the current implementation? Since any ListView.builder will not work with the nested scrollviews right?

**Comment by cryptpa** [comment]
you must use 
`
  shrinkWrap: true,
  physics: const NeverScrollableScrollPhysics(),
`
for any scrollable widget that placed in body.

**Comment by kspo** [comment]
you must use
`shrinkWrap: true, physics: const NeverScrollableScrollPhysics(),`
for any scrollable widget that is placed in the body.

**Comment by eikebartels** [comment]
Hey @kspo thanks for your answer, yes I notice this but thats also is the thing. How can that work with generated lists then? 

Anyway Ill dig deeper to figure out how and will eventually provide an improvement PR :)

**Comment by kspo** [comment]
Sure :) I appreciate any contribution 👍

**Comment by kspo** [comment]
@eikebartels checkout version 2.1.0 from pub.dev. SuperScaffold body can be any widget now
